language: node_js

go:
    - "1.15.2"

node_js:
    - lts/*
    - node

install:
    - wget https://golang.org/dl/go1.15.2.linux-amd64.tar.gz
    - tar xvfs go1.15.2.linux-amd64.tar.gz
    - chmod +x go/bin/go
    - export PATH=$PWD/go/bin:$PATH
    - export GOROOT=$PWD/go
    - go version
    - npm install
    - npx node-gyp configure
    - npx node-gyp rebuild
